services:
  - type: web
    name: crowdfunding-app
    env: python
    plan: free
    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py migrate &&
      python manage.py collectstatic --no-input
    startCommand: gunicorn crowdfunding.wsgi
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        fromService:
          name: crowdfunding-app
          property: host
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: SESSION_COOKIE_SECURE
        value: "True"
      - key: CSRF_COOKIE_SECURE
        value: "True"
      - key: SECURE_HSTS_SECONDS
        value: "31536000"
      - key: SECURE_HSTS_INCLUDE_SUBDOMAINS
        value: "True"
      - key: SECURE_HSTS_PRELOAD
        value: "True"
  
  - type: pserv
    name: crowdfunding-postgres
    ipamNetwork: crowdfunding_network
    plan: free
